server:
  port: ${SCDDATANPS_SERVER_PORT:80}
  context-path: /scddatanps
spring:
  application:
    name: scddatanps
  datasource:
    url: jdbc:postgresql://${SCDDATANPS_SPRING_DATASOURCE_DBHOST}/${SCDDATANPS_SPRING_DATASOURCE_DBNAME}?currentSchema=${SCDDATANPS_SPRING_DATASOURCE_DBSCHEMA}
    username: ${SCDDATANPS_SPRING_DATASOURCE_USER}
    password: ${SCDDATANPS_SPRING_DATASOURCE_PWD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
  jackson:
    serialization:
      write-dates-as-timestamps: false
       
management:
  context-path: /admin
  security:
    enabled: false

logging:
  level:
    com.stratio : ${SCDDATANPS_LOGGING_LEVEL}
