@Library('jenkinslib') _

mavenDockerBuilderPipeline {

  containerName = 'test-maven-app'
  dockerRepo = ''
  registryCredentialsId = 'docker-credentials'
  buildType = 'build'
  pomPath = 'scddatanps/'

}
