@Library('jenkinslib') _

mavenDockerBuilderPipeline {

  containerName = 'sanitas-scddatanps'
  dockerRepo = ''
  registryCredentialsId = 'docker-credentials'
  buildType = 'build'
  pomPath = 'scddatanps/'

}
